seed: 47
n_envs: 8
rl_algorithm: "PPO"
model_name: "duckietown_lane_follower"
total_timesteps: 3000000

simulator_params:
  domain_rand: False
  map_name: "loop_empty"
  max_steps: 500
  draw_curve: False
  draw_bbox: False
  camera_width: 128
  camera_height: 128

model_params:
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 256
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95 
  clip_range: 0.2 
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5