model_name: "scratch_model"
rl_algorithm: "PPO"
total_timesteps: 3  # Ensure you know this will be multiplied by n_envs
n_envs: 1  # Set to 1 if you want exactly 5 steps
seed: 47

duckietown_params:
  map_name: "loop_empty"
  full_transparency: true

model_parameters:
  verbose: 0

training_parameters:
  save_freq: 100  # Still saving every step
  reset_num_timesteps: true  # Ensure the training starts fresh