seed: 47
n_envs: 16
rl_algorithm: "SAC"
model_name: "SAC_lr0.0001_buf1000000_ls4096_bs256_tau0.005_gamma0.98_tf1_gs1_ent0.05"
total_timesteps: 5000000

checkpoint_save_freq: 15000
video_save_freq: 15000

simulator_params:
  domain_rand: False
  map_name: "small_loop"
  max_steps: 250
  draw_curve: False
  draw_bbox: False
  camera_width: 84
  camera_height: 84

model_params:
  learning_rate: 0.0001
  buffer_size: 1000000
  learning_starts: 4096
  batch_size: 256
  tau: 0.005
  gamma: 0.98
  train_freq: 1
  gradient_steps: 1
  ent_coef: 0.05